spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db20220622131607_high?TNS_ADMIN=C:/Backshi/Wallet_DB20220622131607
    username: admin
    password: '!Zz9902191178926zz'

